name: youtube_player
description: A Plugin that allows you to playe Youtube videos without apikey in Android devices. fully customizable.
version: 0.0.1
author: null
homepage: null

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  lint: ^1.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: kannel.outtis.youtube_player
        pluginClass: YoutubePlayerPlugin